services:

  postgres-auth:
    image: postgres:17.0-alpine3.20
    container_name: postgres-auth

    env_file:
      - .env

    volumes:
      - postgres_auth_data:/var/lib/postgresql/data

    ports:
      - "${EXTERNAL_POSTGRES_PORT}:5432"

    healthcheck:
      # Проверяем готовность базы с помощью встроенной команды pg_isready, используя логин из .env
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped

    networks:
      - microservices-net

  redis-auth:
    image: redis:7.2.5-alpine3.20
    container_name: redis-auth

    env_file:
      - .env

    ports:
      - "${EXTERNAL_REDIS_PORT}:6379"

    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped

    networks:
      - microservices-net

volumes:
  postgres_auth_data:

networks:
  microservices-net:
    external: true