services:

  mongo-inventory: # Контейнер с MongoDB — используется для хранения данных об инвентаре (например, запчасти, компоненты)
    image: ${MONGO_IMAGE_NAME}

    container_name: mongo-inventory

    env_file:
      - .env

    volumes:
      - mongo_inventory_data:/data/db

    ports:
      - "${EXTERNAL_MONGO_PORT}:27017"

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "echo 'db.runCommand({ ping: 1 }).ok' | mongosh --quiet -u ${MONGO_INITDB_ROOT_USERNAME} -p ${MONGO_INITDB_ROOT_PASSWORD} --authenticationDatabase admin --authenticationDatabase ${MONGO_AUTH_DB}",
        ]
      # Проверка готовности MongoDB: выполняем команду ping через mongosh с указанием логина и пароля
      # --quiet отключает лишний вывод, чтобы результатом был только "1" при успехе
      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped
    # Автоматически перезапускаем контейнер, если он аварийно завершился
    # Но если мы остановим его вручную — он не запустится повторно

    networks:
      - microservices-net

volumes:
  mongo_inventory_data:

networks:
  microservices-net:
    external: true
