services:

  mongo-inventory: # Контейнер с MongoDB — используется для хранения данных об инвентаре (например, запчасти, компоненты)
    image: mongo:7.0.5

    container_name: mongo-inventory

    environment:
      MONGO_INITDB_DATABASE: inventory-service
      MONGO_INITDB_ROOT_USERNAME: inventory-service-user
      MONGO_INITDB_ROOT_PASSWORD: inventory-service-password

    volumes:
      - mongo_inventory_data:/data/db

    ports:
      - "27017:27017"

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "echo 'db.runCommand({ ping: 1 }).ok' | mongosh --quiet -u inventory-service-user -p inventory-service-password --authenticationDatabase admin",
        ]
      # Проверка готовности MongoDB: выполняем команду ping через mongosh с указанием логина и пароля
      # --quiet отключает лишний вывод, чтобы результатом был только "1" при успехе
      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped
    # Автоматически перезапускаем контейнер, если он аварийно завершился
    # Но если мы остановим его вручную — он не запустится повторно

    networks:
      - microservices-net

volumes:
  mongo_inventory_data:

networks:
  microservices-net:
    external: true
